#!/bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          37

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true
bspc config urgent_border_color "#72003e"

xsetroot -cursor_name left_ptr &
redshift -l 39.866397:-83.074054 &
feh --bg-fill ~/Downloads/wallhaven-242954.png
btops &
polybar main &
light -S 1 &
xss-lock -- lock

xrdb -I$HOME ~/.Xresources

source "$HOME/.Xresources"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"
